version: '3.9'
services:
  clin-portal-forms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    mem_limit: "512m"
    mem_reservation: "256m"
    cpus: 1
    cpuset: "1"
    network_mode: host
    healthcheck:
      test: curl -Is localhost:8080/actuator/health | head -n 1 | grep 200 || exit 1
      interval: 10s
      timeout: 2s
      retries: 10