spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
fhir:
  url: ${FHIR_URL:https://fhir.qa.cqgc.hsj.rtss.qc.ca/fhir}
  timeout: 5000
  pool-size: 20
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
security:
  enabled: ${SECURITY_ENABLED:true}
  audience: ${SECURITY_AUDIENCE:clin-acl}
  issuer: ${SECURITY_ISSUER:https://auth.qa.cqgc.hsj.rtss.qc.ca/auth/realms/clin}
  cors:
    - "http://localhost:2000"
    - "https://portail.qa.cqgc.hsj.rtss.qc.ca"
    - "https://portail.staging.cqgc.hsj.rtss.qc.ca"
    - "https://portail.cqgc.hsj.rtss.qc.ca"
