server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 2048
spring:
  application:
    name: Forms (API)
  main:
    lazy-initialization: true
  resources:
    cache:
      cachecontrol:
        max-age: 36000
        must-revalidate: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: true
      additional-paths: templates/
fhir:
  url: ${FHIR_URL:https://fhir.qa.cqgc.hsj.rtss.qc.ca/fhir}
  timeout: 15000
  pool-size: 20
  validate: false
  supported-langs:
    - fr
  types-with-default: # will load <type>-default-hpo <type>-default-exam 
    - mmg
    - mitn
    - rgdi
  same-types: # use the same 'types-with-default'
    DYSM: MMG
    HYPM: MMG
    MYAC: MMG
    MYOC: MMG
    RHAB: MMG
  multi-values-observation-codes: # will load <code>-abnormalities
    - bmus
    - emg
cache:
  eviction: 3600 # 1h
management:
  endpoints:
    web:
      exposure:
        include: health,status
  endpoint:
    #logfile:
      #external-file: "./logs/app.log"
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
security:
  leeway: 5 # seconds
  enabled: ${SECURITY_ENABLED:true}
  audience: ${SECURITY_AUDIENCE:clin-acl}
  issuer: ${SECURITY_ISSUER:https://auth.qa.cqgc.hsj.rtss.qc.ca/realms/clin}
  system: "clin-system"
  cors:
    - "*"
  publics:
    - "/actuator/health"
logging:
  file:
    name: "./logs/app.log"
    max-history: 3
    max-size: 1MB
  level:
    root: ERROR
    org.springframework.web: ERROR
    bio.ferlab.clin.portal.forms: INFO
    org.hibernate: ERROR
status:
  enabled: ${STATUS_ENABLED:false}
  logs-size: 50
pebble:
  strictVariables: false